[default_session]

[[session]]
name = "ï€™  Downloads"
path = "~/Downloads"

[[session]]
name = "ó°ˆ™ Documents"
path = "~/Documents"

[[session]]
name = "ï€  Music"
path = "~/Music"

[[session]]
name = "ï€¾  Pictures"
path = "~/Pictures"

[[session]]
name = "ğŸ Dotfiles"
path = "~/code/dotfiles/"
startup_command = "vim"

[[session]]
name = "ğŸ¢ Cerberos"
path = "~/code/cerberos/"

[[session]]
name = "ğŸ³ CRB-Dock"
path = "~/code/crb-dock/"

[[session]]
name = "ğŸš€ Clients"
path = "~/code/clients/"

[[session]]
name = "ğŸ’€ Marzun"
path = "~/code/marzun/"
