[default_session]

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "ll"

[[session]]
name = "ğŸ“¦ Dotfiles"
path = "~/code/dotfiles/"
startup_command = "vim"

[[session]]
name = "ğŸ¢ Cerberos"
path = "~/code/cerberos/"

[[session]]
name = "ğŸ³ CRB-Dock"
path = "~/code/crb-dock/"

[[session]]
name = "ğŸš€ Clients"
path = "~/code/clients/"

[[session]]
name = "ğŸğŸ’¨ Marzun"
path = "~/code/marzun/"
